name=CryptnoxSDK
version=1.0.0
author=Cryptnox
maintainer=Cryptnox
sentence=Arduino library for Cryptnox Smart Card wallets.
paragraph=Hardware-agnostic API to connect to Cryptnox cards over NFC (PN532), establish secure channels, verify PINs, and sign hashes.
category=Communication
url=https://github.com/embarquech/cryptnox-sdk-arduino
architectures=*
depends=micro-ecc,Adafruit PN532,AESLib,Crypto
