@startuml
title Cryptnox SDK Arduino - Layered architecture

package "Cryptnox SDK Cpp" <<Frame>> {
package "Library" {
    class CryptnoxWallet {
        + CryptnoxWallet(nfcDriver, logger)
        + begin()
        + connect(session)
        + establishSecureChannel(session)
        + disconnect(session)
        + getCardInfo(session)
        + verifyPin(session)
        --
        - logger : CW_Logger&
        - secure : CW_SecureChannel
    }
}

package "Secure stack" {
    class CW_SecureChannel {
        + selectApdu(session, nfcDriver, logger, ...)
        + openSecureChannel(session, driver, logger, ...)
        + mutuallyAuthenticate(session, nfcDriver, logger, ...)
        + aesCbcEncrypt(session, nfcDriver, logger, ...)
        + aesCbcDecrypt(session, nfcDriver, logger, ...)
        + checkStatusWord(...)
        --
        - crypto : CW_CryptoProvider
        - nfcDriver : CW_NfcTransport&
    }

    class CW_SecureSession {
        + aesKey[...]
        + macKey[...]
        + iv[...]
        --
        + CW_SecureSession()
        + clear() : void
    }
}

package "Crypto abstraction" {
    abstract class CW_CryptoProvider {
        + sha512(...)
        + aesCbcEncrypt(...)
        + aesCbcDecrypt(...)
        + ecdh(...)
        + random(...)
    }

    class ArduinoCryptoProvider {
        + sha512(...)
        + aesCbcEncrypt(...)
        + aesCbcDecrypt(...)
        + ecdh(...)
        + random(...)
        --
        - aes : AESLib
        - sha : SHA512
    }
}

package "Transport" {
    abstract class CW_NfcTransport {
        + begin()
        + inListPassiveTarget()
        + sendAPDU(logger, ...)
        + resetReader()
        + printFirmwareVersion(logger, ...)
    }

    class PN532Adapter {
        + begin()
        + sendAPDU(logger, ...)
        + inListPassiveTarget()
        + resetReader()
        + printFirmwareVersion(logger, ...)
        --
        - nfc : Adafruit_PN532*
    }
}

package "Logging" {
    abstract class CW_Logger {
        + begin()
        + print(...)
        + println(...)
    }

    class ArduinoLoggerAdapter {
        + ArduinoSerialAdapter(serial)
        + print(...)
        + println(...)
        --
        - serial : HardwareSerial*
    }
}
}

package "External Libraries" <<Frame>> #FFFDE7 {
    
    class Adafruit_PN532 <<library>> {
        + begin() : void
        + inDataExchange() : bool
        + readPassiveTargetID() : bool
        + SAMConfig() : void
        + getFirmwareVersion() : uint32_t
    }
    
    class AESLib <<library>> {
        + set_paddingmode(mode) : void
        + encrypt(input, len, output, key, keyLen, iv) : uint16_t
        + decrypt(input, len, output, key, keyLen, iv) : uint16_t
    }
    
    class "uECC (micro-ecc)" as uECC <<library>> {
        + uECC_secp256r1() : uECC_Curve_t
        + uECC_make_key(pubKey, privKey, curve) : bool
        + uECC_shared_secret(pubKey, privKey, secret, curve) : int
        + uECC_set_rng(rng_callback) : void
    }

    class SHA512 <<library>> {
        + update(data, len) : void
        + finalize(output, len) : void
    }

    class HardwareSerial <<Arduino>> {
        + begin(baudRate) : void
        + print(...) : size_t
        + println(...) : size_t
    }
}

' ==============================
' Relations principales
' ==============================

CryptnoxWallet --> CW_SecureChannel
CryptnoxWallet --> CW_Logger
CW_SecureChannel *.. CW_SecureSession
CW_SecureChannel --> CW_CryptoProvider
CW_SecureChannel --> CW_NfcTransport

CW_CryptoProvider <|.. ArduinoCryptoProvider
CW_NfcTransport <|.. PN532Adapter
CW_Logger <|.. ArduinoLoggerAdapter


ArduinoLoggerAdapter --> HardwareSerial

ArduinoCryptoProvider *-- "1" AESLib
ArduinoCryptoProvider ..> uECC
ArduinoCryptoProvider *-- "1" SHA512
PN532Adapter *-- "1" Adafruit_PN532

@enduml
